# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: kb1
# app and org for use with dashboard.serverless.com
app: kb1-crm-app
org: guy1812

provider:
  name: aws
  apiKeys:
    - access_crm_query_key_${self:provider.stage}
  runtime: nodejs12.x
  timeout: 10
  stage: ${opt:stage, self:custom.default_stage}
  environment:
    APIG_DEPLOYMENT_ID: ApiGatewayDeployment${sls:instanceId}
    STAGE: ${self:provider.stage}
    SECRETS: ${self:custom.secrets}

#  iamRoleStatements:
#    - Effect: 'Allow'
#      Action:
#        - 'lambda:InvokeFunction'
#      Resource: "*"

functions:
  returnNotValid:
    handler: src/functions/returnNotValid.returnNotValid
    events:
      - http:
          path: returnNotValid
          method: post

  sendReplies:
    handler: src/functions/sendMsgAsUser.sendMsgAsUser
    events:
      - http:
          path: sendReplies
          method: post

  existByPhone:
    handler: src/functions/existOnCrm.existByPhone
    #    warmup: true
    events:
      - http:
          path: crm/existByPhone
          method: post
          private: true

  checkForMessenger:
    handler: src/functions/existOnCrm.existByPhone
    events:
      - http:
          path: crm/checkForMessenger
          method: post
          private: true

  registerNotificationKey:
    handler: src/functions/notifications.registerNotificationKey
    events:
      - http:
          path: notifications/registerNotificationKey
          method: post
          private: false

  sendNotifications:
    handler: src/functions/notifications.sendNotifications
    events:
      - http:
          path: notifications/send
          method: post
          private: true

  checkNotificationPushStatus:
    handler: src/functions/notifications.checkNotificationPushStatus
    events:
      - http:
          path: notifications/send
          method: post
          private: true

  createOrder:
    handler: src/functions/orders.create
    events:
      - http:
          path: crm/orders/create
          method: post
          private: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-jest-plugin
  - serverless-domain-manager
  - '@serverless/enterprise-plugin'

custom:
  #secrets: '${ssm:/aws/reference/secretsmanager/serverless-crm-kbp~true}'
  default_stage: dev
  jest:
    collectCoverage: true
  serverless-offline:
    useChildProcesses: true